### ISSUE TITLE
Create Kanban / project view to track progress

### ISSUE THREAD

**Issue by andreaczhang** [PSIAIMS/CAMIS#106]
Can be helpful to have an overview of what is being worked on.

**Comment by DrLynTaylor** [comment]
I think we decided to do this via the Issues tab.  https://github.com/PSIAIMS/CAMIS/issues instead of separate method?  Can this be closed?

**Comment by andreaczhang** [comment]
> I think we decided to do this via the Issues tab. https://github.com/PSIAIMS/CAMIS/issues instead of separate method? Can this be closed?

Of course! Close please :) @DrLynTaylor
