### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by andreaczhang** [PSIAIMS/CAMIS#138]
Remove Home

About 

Contribution 
- another section for datasets
- (possibility to split the contribution page into smaller articles) 

Blog (maybe wait until we have 3 or more blogs)

Updates (what's new) tab
- meeting minutes
- conferences 2024 (link to the poster / material in whitepaper)

Publications 
- whitepaper

**Comment by DrLynTaylor** [comment]
@statasaurus  and @andreaczhang .  I needed to put Soma's US Connect poster into the repo, so I created a Conferences 2023 and 2024 folder under "non-website" content.  I will link to his poster from the Conferences.qmd as well.  We had 2 blog posts in this non-website conent folder, so I moved them under a blog folder, but if you want them somewhere else feel free to move them when you set up where future blogs are going to belong.  I plan to archive the conferences.qmd each year into this folder as a summary (like the 2023 one is now). Happy to discuss if this is the best approach!

**Comment by DrLynTaylor** [comment]
proposed links:
	[Makes R Easier for Everyone • sassy (r-sassy.org)](https://urldefense.com/v3/__https:/sassy.r-sassy.org/index.html__;!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMbpxIGrLw$)
	SAS-R code converter:   Subscription if >10 conversions or over 1500 characters.   [SAS to R Converter (codeconvert.ai)](https://urldefense.com/v3/__https:/www.codeconvert.ai/sas-to-r-converter__;!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMaiRtH4xg$)
	Other researchers have recently published material comparing statistical software programs for common parametric analyses as well as more complex statistical models 
	(Bergmann et al., [2000]([https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-CR5](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-CR5__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMYpUrfaNQ$) [https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-cr5](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-cr5__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMbnmD6g0A$)); 
	Brown et al., [2012]([https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-CR10](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-CR10__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMbVBUadtg$) [https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-cr10](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-cr10__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMYF5Hw6fA$)); 
	McCoach et al., [2018]([https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-CR43](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-CR43__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMbT54LI3g$) [https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-cr43](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-cr43__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMaYyOgteg$)); 
	Oster & Hilbe, [2008a]([https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-CR55](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-CR55__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMZLvd4NpQ$) [https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-cr55](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-cr55__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMacWhdqdA$)), 
	[2008b]([https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-CR56](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-CR56__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMavq_Xa1A$) [https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-cr56](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-cr56__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMYJqgVqXA$)); 
	Wang & Johnson, [2019]([https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-CR68](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-CR68__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMapoaOW-A$) [https://link.springer.com/article/10.3758/s13428-022-01932-2#ref-cr68](https://urldefense.com/v3/__https:/link.springer.com/article/10.3758/s13428-022-01932-2*ref-cr68__;Iw!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMZs1Ca0jA$)))."  
	[https://pubmed.ncbi.nlm.nih.gov/35953660/](https://urldefense.com/v3/__https:/pubmed.ncbi.nlm.nih.gov/35953660/__;!!AoaiBx6H!2RIkvbJ_wI5-xEH5gw4aaE0MzOxn2_f9XiKrB20Ijxqu0rHf8LS0eaOzGywK3xRUrZkCJFkJff8gFM7BIQigcMa7VGZhrw$)
