### ISSUE TITLE
Add more information about the version of R running and package

### ISSUE THREAD

**Issue by statasaurus** [PSIAIMS/CAMIS#139]

**Comment by michaelwalshe** [comment]
Hi @statasaurus, following on from a comment I made at the community meeting, I think it's important to show the less technical readers of the page the R and package version information, without them having to go to the renv.lock file on GitHub. Packages may be updated to change numerical results or methods, fix bugs, or add features, all of which could change the results of a comparison.

A good way to include the necessary info for a page on what packages and R versions have been used could be to use something like `sessionInfo("packagename")`. This creates a bit too much output by default, so an alternative is to use `sessioninfo::session_info("packagename")` from the [`{sessioninfo}`](https://sessioninfo.r-lib.org/) package, this could be in a collapsed note section at the end of each page, with the call to `session_info()` customised depending on the packages used in that page. This will only list info for the package(s) requested and their hard dependencies.

An example section could be:
````
::: {.callout-note collapse=true title="Session Info"}
```{r}
#| echo: false
sessioninfo::session_info("emmeans")
```
:::
````

Which produces:
![image](https://github.com/PSIAIMS/CAMIS/assets/62556482/7af27bca-1b01-4ed6-91cc-f0a0715de74c)

When expanded:
![image](https://github.com/PSIAIMS/CAMIS/assets/62556482/baf79ff6-3ec5-47a2-ae6f-9e61a4f71380)

It would also be useful to include the SAS version where appropriate, this would have to be manually added by a contributer but can be easily determined:
```
%put SAS Version: &SYSVLONG;
SAS Version: 9.04.01M7P080520
```

And then either printed in the same section as-is, or can be included under external software:

````
::: {.callout-note collapse=true title="Session Info"}
```{r}
#| echo: false
si <- sessioninfo::session_info("emmeans")
si$external <- structure(list("SAS" = "9.04.01M7P080520"), class = c("external_info", "list"))
si
```
:::
````
![image](https://github.com/PSIAIMS/CAMIS/assets/62556482/4ff42b35-f10a-4f23-a887-c861e8fb9916)

Let me know what you think, I'm happy to contribute this if you think it would be worthwhile, though wouldn't be able to include the SAS info as that depends on the original contributor. I'm also working on another contribution of a comparison of survey methods, but it's a bit on the backburner as there is more to cover than I first thought!

**Comment by statasaurus** [comment]
I might be wrong here, but I am pretty sure the issue is that because each page is rendered together the session info will be a bit random, base on which pages have been run prior to the current page. So it will have all packages used on the page plus any packages needed by previously rendered pages. Would you be able to test this?

**Comment by michaelwalshe** [comment]
From building the site after adding the above to a couple of pages, it seems to work quite well and isn't polluted with previously loaded packages. Some of the packages (e.g. `{broom}`) have quite a lot of dependencies, and so do lead to a fairly long session info section, so I might suggest adding `dependencies = FALSE` to just display the version of the main package.

Another thing I noticed is that some packages are used as examples but aren't evaluated, so the package isn't added as a dependency (e.g. `{epiDisplay}` in https://psiaims.github.io/CAMIS/R/cmh.html). I'm not sure how we'd want to report on this, the package is not installed so there's no version report, but it's evaluated for its features (or lack thereof) based on a version (I assume the latest). Maybe adding a last published/revised date to each page?

See below for screenshots of examples rendered as part of the whole site:

![image](https://github.com/PSIAIMS/CAMIS/assets/62556482/471b019f-d2e1-497c-b0bd-35e618041521)

![image](https://github.com/PSIAIMS/CAMIS/assets/62556482/4e950058-0a8c-47be-9827-6dc2fff1a5df)

**Comment by statasaurus** [comment]
I have added this into the templates. Thank you @michaelwalshe for doing this 😃 Once this is approved I will close this issue

**Comment by michaelwalshe** [comment]
Happy to help! Just a note @statasaurus - it looks like the snippet in the template is indented by 1 space, which means the ` #| echo: false` isn't getting picked up. E.g. https://psiaims.github.io/CAMIS/Comp/r-sas_survival_cif.html

**Comment by statasaurus** [comment]
Ahh I have had so many spacing issues!! Let me fix again
