### ISSUE TITLE
Add freeze option to articles

### ISSUE THREAD

**Issue by michaelwalshe** [PSIAIMS/CAMIS#173]
Currently, each time the site is rendered via `quarto render`, every .qmd file is re-rendered and executed. This may cause issues in the future, as the R and R packages are updated old code can cause warnings, errors, or changes in results in previously accurate comparisons. It could also be harder to add new packages with conflicting dependencies (less of an issue in R, but more so in Python).

I think it would be beneficial to avoid this, by adding to the Quarto yaml header the [freeze](https://quarto.org/docs/projects/code-execution.html) option:

```yaml
execute:
  freeze: true  # never re-render during project render
```

or
```yaml
execute:
  freeze: auto  # re-render only when source changes
```

We would also need to include details of when the page was last updated and the package versions used to execute a page.

**Comment by statasaurus** [comment]
We actually kind of want those issues. If someone needs to up versions a package that causes someone else's page to break I would rather it errors such that it will fail the checks we have in place.

**Comment by michaelwalshe** [comment]
I guess that makes sense, it's whether the site is an up-to-date state of the comparison, or an archive of the changes. I had thought it could be too much work to keep all pages up to date, so better to freeze them as-of publication and then updating when necessary. But happy to close this if that's not the direction
