### ISSUE TITLE
Statistic Comparison Table Incorrect

### ISSUE THREAD

**Issue by michaelwalshe** [PSIAIMS/CAMIS#179]
I think the current live stat table is incorrect, it's missing links that had been completed e.g. in Ancova:

![image](https://github.com/PSIAIMS/CAMIS/assets/62556482/aafe21d0-073e-45f5-ab84-059cd40d044b)

I believe commit 1fa243c from #166 was using an old stat table.

**Comment by DrLynTaylor** [comment]
Thanks @michaelwalshe,  you are correct.. when we've added python somethings got lost.  @statasaurus  another one to look at when you have time !

**Comment by statasaurus** [comment]
yeah there was a merge conflict I tired to copy everything clearly missed this I will fix thank you for catching
