### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by LukasBrausch** [PSIAIMS/CAMIS#187]
Hello everyone,

I just noticed that a license file seems to be missing for this project. I reckon that we should have one, as a proper open source project. :) Personally, I would recommend going with the GPL, but I know that this can be a very delicate topic, and I'm open for discussion if anybody has any other preferences.

Thank you very much and have a nice day.

Best regards,
Lukas

**Comment by LukasBrausch** [comment]
Hi @michaelwalshe,

Thanks a lot for your comments. The document you provided states the following:

> As a general guidance, if the purpose of the project is to let future contributors freely use the
> code, MIT license is a concise permissive license to adopt. In the pharmaceutical industry,
> however, the patent of the code is often of concern in a post-competitive environment across
> companies, and thus an Apache 2.0 license could be more suitable. On the other hand, the
> copyleft license (e.g. GPLv2, GPLv3) demands any downstream derivatives to follow the same
> copyleft license of the source project and generally should be avoided.

Thus, I agree that choosing either the MIT or Apache 2.0 license should be a good idea in general.

**Comment by statasaurus** [comment]
Sorry this was on the on the to do list and it just fell off my radar. I have added the apache 2.0 license. Thank you for flagging this
