### ISSUE TITLE
Overall structure

### ISSUE THREAD

**Issue by therneau** [PSIAIMS/CAMIS#200]
I wrote a longer post in the discussions section.   If that is the wrong place for a higher level discussion please let me know.

**Comment by DrLynTaylor** [comment]
Thanks for the discussion...  I'll have a read and get back to you in the next couple of days.

**Comment by DrLynTaylor** [comment]
Let's discuss it at our next leaders meeting. some important thoughts we need to consider to ensure the project is on the right track !  This issue just reminds me it's still on our list to fully discuss as a team: https://github.com/PSIAIMS/CAMIS/discussions/199
