### ISSUE TITLE
df_disease dataframe from SAS documentation

### ISSUE THREAD

**Issue by LukasBrausch** [PSIAIMS/CAMIS#204]
Hello everyone,

Today, I was planning to implement the Python ANOVA part. To do that, I took a look at the corresponding [R counterpart](https://psiaims.github.io/CAMIS/R/anova.html) first.

Concerning the underlying data, I found the following statement:

> Getting Started
> 
> To demonstrate the various types of sums of squares, we’ll create a data frame called df_disease taken from the SAS documentation.

Unfortunately, I wasn't able to find that data frame in the SAS documentation. Could anyone please point me to that data? Furthermore, I reckon that it would be a good idea to specifically mention the used data for each method. If the input is explicitly known, it would make it much easier for people to follow along and compare methods,

Thank you very much for your guidance and have a nice day.

**Comment by statasaurus** [comment]
The data is here. https://github.com/PSIAIMS/CAMIS/blob/main/data/sas_disease.csv

**Comment by LukasBrausch** [comment]
Thank you very much for pointing me to the right data. I added a link to the data in my last PR.
