### ISSUE TITLE
Generalized Linear Models	- Logistic Regression

### ISSUE THREAD

**Issue by statasaurus** [PSIAIMS/CAMIS#24]

**Comment by alex-lauer** [comment]
@jmanitz and me would like to take over the R part.

**Comment by jmanitz** [comment]
[pull request](https://github.com/PSIAIMS/CAMIS/pull/102) submitted

**Comment by DrLynTaylor** [comment]
Hi @alex-lauer @molmac @jmanitz .   Great to have this R part completed,  are any of you working on the SAS part & comparison?  @bvarney9 offered to help if needed so just wondered if anyone had started.

**Comment by molmac** [comment]
@DrLynTaylor I haven't managed the SAS part or comparison yet so would be happy for this to be handed over

**Comment by DrLynTaylor** [comment]
@bvarney9 -  If you do get any time, it would be great if you can do the SAS part for Logistic regression

**Comment by CraigWangStat** [comment]
Hi all, A few of us at Novartis started working on the comparison between R vs SAS for logistic regression (default, firth, g-computation)

**Comment by DrLynTaylor** [comment]
That's fantastic @CraigWangStat  as we didn't get chance to make any further progress -  If you have any questions or need any help to complete the pull request just reach out to me   or @statasaurus

**Comment by CraigWangStat** [comment]
> That's fantastic @CraigWangStat as we didn't get chance to make any further progress - If you have any questions or need any help to complete the pull request just reach out to me or @statasaurus

Thanks! PR is now in #253
