### ISSUE TITLE
Rounding in R.

### ISSUE THREAD

**Issue by DrLynTaylor** [PSIAIMS/CAMIS#299]
https://github.com/PSIAIMS/CAMIS/blob/5e19d3d0ac003e46dca043f203b3c844bb8ecca4/R/rounding.qmd#L7

We need to reword this "zero. in" and the NOTE  reads a little strange.  Also introduce digits = x before using it.
Make it more like the R template with different sections for each package

**Comment by ddsjoberg** [comment]
Hi @DrLynTaylor , if it makes a difference, we have a pharmaverse package that has the same functionality.
https://insightsengineering.github.io/cards/latest-tag/reference/round5.html

**Comment by DrLynTaylor** [comment]
Thanks. I'll add into Camis repo
