### ISSUE TITLE
Non-parametric Analysis	- Mann-Whitney U/Wilcoxon rank sum

### ISSUE THREAD

**Issue by statasaurus** [PSIAIMS/CAMIS#30]

**Comment by andreaczhang** [comment]
Similar to #29 , I would like to give it a try :)

**Comment by DrLynTaylor** [comment]
@AgnieszkaTomczyk  - just assigned this section to you as I know you are working with @andreaczhang on this topic.

**Comment by andreaczhang** [comment]
@statasaurus I think my chapter that you merged in the website for this topic is put under **Wilcoxon signed rank**, instead of **Wilcoxon rank sum** :) Could you have a look when you have time? Thank you! 😊

**Comment by statasaurus** [comment]
Okay should be fixed now, sorry I was not reading closely when I put it in the table
