### ISSUE TITLE
SAS output for quantiles

### ISSUE THREAD

**Issue by DrLynTaylor** [PSIAIMS/CAMIS#302]
https://github.com/PSIAIMS/CAMIS/blob/5e19d3d0ac003e46dca043f203b3c844bb8ecca4/SAS/summary-stats.qmd#L8

Change title to be Calculating Quantiles (percentiles) in SAS.  to highlight they are the same thing
Add some text to say that the Q1= 25%,  Q2=50%, Q3 = 75%, 
Update to have the output coming out using same dataset as in R page

**Comment by alanahjonas95** [comment]
@DrLynTaylor From what i can see the example in the r page is the same as the sas one? so not sure what needs updating?

**Comment by DrLynTaylor** [comment]
Thanks @alanahjonas95    That's odd !! But I agree, example looks the same so I think we are done with this issue and it can be closed.  Thanks so much :)
