### ISSUE TITLE
PYthon ANOVA 1 way

### ISSUE THREAD

**Issue by DrLynTaylor** [PSIAIMS/CAMIS#311]
https://github.com/PSIAIMS/CAMIS/blob/5e19d3d0ac003e46dca043f203b3c844bb8ecca4/python/anova.qmd#L25

- [x] add a ANOVA 1 way in python... and compare results to R / SAS using same data
- [x] explain how to do type 1 SS, Type 2 SS, type 3 SS, type 4 SS (if possible) or say they arne't possible
- [x] Add detail of what SS the default is in python

**Comment by seemaniabhilipsa** [comment]
Can I work on this issue ?

**Comment by DrLynTaylor** [comment]
@statasaurus  and @seemaniabhilipsa  - do you think we can close this issue now?  We have great detail on SS in the ANCOVA python page.    I think the only thing missing is in the ANCOVA page you found that "Please note that the results are consistent with the results achieved with [R](https://psiaims.github.io/CAMIS/R/ancova.html), except for the first row of the type 3 table featuring the intercept."  do we know why this didnt' agree? perhaps a separate issue to raise for someone to investigate?  So we can say it didn't agree because...    Where things do agree (like for ANOVA with type II sums of square). it would be good to add that sentence, i.e.  as the bottom of here: https://psiaims.github.io/CAMIS/python/anova.html    "The ANOVA model using type II sums of squares matched the results of both SAS & R"?

**Comment by seemaniabhilipsa** [comment]
Sure I can put the comment and check for the discrepancy in results
