### ISSUE TITLE
Categorical Data Analysis	- Confidence Intervals for proportions

### ISSUE THREAD

**Issue by statasaurus** [PSIAIMS/CAMIS#40]

**Comment by fernhughes** [comment]
Hi @dbosak01  - are you still working on this topic? I would be interested in contributing

**Comment by dbosak01** [comment]
Hi @fernhughes .  No, I've had some family issues to take care of, and I can't work on it any more.  It's all yours!

**Comment by DrLynTaylor** [comment]
Great that we now have R content in for normal approximation.  Still plenty to do on this topic though if any fancies it.

- [ ] Normal approximation for SAS - (This is also called asymptotic or wald )
- [ ] Normal approximation comparison SAS vs R
- [ ] Normal approximation comparison Python
- [ ] Exact (Clopper Pearson) binomial CIs (SAS )
- [ ] Exact (Clopper Pearson) binomial CIs ( R)
- [ ] Exact (Clopper Pearson) binomial CIs (Comparison SAS vs R vs Python)
- [ ] Altman Machin Method
- [ ] Wilson (Score) method - better for small samples and where P is at or near 0 or 1.
- [ ] Aresti-Coull (AC) method
- [ ] Bayesian HPD
perhaps we cross reference the following? 
https://towardsdatascience.com/five-confidence-intervals-for-proportions-that-you-should-know-about-7ff5484c024f
