### ISSUE TITLE
Correlation	- Spearman's correlation coefficient

### ISSUE THREAD

**Issue by statasaurus** [PSIAIMS/CAMIS#50]

**Comment by alex-lauer** [comment]
@jmanitz and me would like to take over the R part.

**Comment by DrLynTaylor** [comment]
@alex-lauer and @jmanitz -  Yes please for all of your comments :)  Let us know if you need help getting started.

**Comment by alex-lauer** [comment]
@DrLynTaylor: Thanks for the offer. We're fine. Our little coding session hasn't officially started yet, but we'll have a dedicated meeting series for CAMIS next month - it's going to be our summer camp 😊

**Comment by jmanitz** [comment]
Pull request submitted
