### ISSUE TITLE
Sample size /Power calculations	- Group-sequential designs

### ISSUE THREAD

**Issue by statasaurus** [PSIAIMS/CAMIS#59]

**Comment by yuliasidi** [comment]
Is there an interest to make a comparison of R vs EAST? If so, I am interested to contribute on that topic

**Comment by statasaurus** [comment]
Hello @yuliasidi, we would love to have comparisons with R and EAST. It would be really good

**Comment by yuliasidi** [comment]
@statasaurus, the initial examples for R and EAST were added in PR https://github.com/PSIAIMS/CAMIS/pull/231 
Still working on the comparison between the two.

**Comment by DrLynTaylor** [comment]
@yuliasidi Thanks for adding the EAST & R content.  Could you write us a short comparison saying whether the methods you use in both software matched?   You could either update the EAST one to say "As you can see results match the R page" and link to that... or if there are discrepancies, add a new page "R vs East" discussion the differences.

**Comment by yuliasidi** [comment]
Sorry for taking so long. PR for this was finally submitted
[https://github.com/PSIAIMS/CAMIS/pull/356#issue-2691891187](url)

**Comment by DrLynTaylor** [comment]
Thank you so much @yuliasidi , we will pull it in this week hopefully
