### ISSUE TITLE
pharmaverse/ggsurvfit integration?

### ISSUE THREAD

**Issue by ddsjoberg** [PSIAIMS/CAMIS#96]
Hello! 🍁 

The ggsurvfit package was recently added to the pharmaverse. The package visualizes survival data, and more details about its addition to the pharmaverse are here: https://github.com/pharmaverse/pharmaverse/issues/231

@MichaelRimler requested I connect with this initiative for user testing. I've done some reading about the project, and I am not 100% clear what the next steps would be. But I wanted to reach out, and let you know I am happy to assist/document in any way needed.

Would the next step be do update the survival analysis section with {ggsurvfit} code?

Thank you!

**Comment by andreaczhang** [comment]
Can I try this out? @ddsjoberg (I was at the R Basel meeting and heard about ggsurvfit, looks cool!)
